-- MySQL Script generated by MySQL Workbench
-- Tue Aug 16 22:04:29 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asi2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asi2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asi2` DEFAULT CHARACTER SET utf8 ;
USE `asi2` ;

-- -----------------------------------------------------
-- Table `asi2`.`ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`ruta` (
  `id_ruta` INT NOT NULL,
  `ruta` VARCHAR(45) NULL,
  PRIMARY KEY (`id_ruta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asi2`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`cargo` (
  `id_cargo` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `activo` CHAR(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asi2`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`empleado` (
  `id_empleado` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(500) NULL,
  `telefono` VARCHAR(10) NULL,
  `celular` VARCHAR(10) NULL,
  `edad` SMALLINT(2) NOT NULL,
  `cargo` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `id_cargo_fk_idx` (`cargo` ASC),
  CONSTRAINT `id_cargo_fk`
    FOREIGN KEY (`cargo`)
    REFERENCES `asi2`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asi2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(255) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL DEFAULT NOW(),
  `estado` ENUM('A','B'),
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `estado_idx` (`estado` ASC),
  INDEX `fk_usuario_empleado1_idx` (`id_empleado` ASC),
  CONSTRAINT `fk_usuario_empleado1`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `asi2`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asi2`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`rol` (
  `id_rol` INT NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `activo` CHAR(1) NOT NULL DEFAULT 'A' COMMENT '		',
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asi2`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`menu` (
  `id_menu` INT NOT NULL,
  `nombre` VARCHAR(200) NULL,
  `rol` INT NULL,
  PRIMARY KEY (`id_menu`),
  INDEX `id_rol_fk_idx` (`rol` ASC),
  CONSTRAINT `id_rol_fk`
    FOREIGN KEY (`rol`)
    REFERENCES `asi2`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asi2`.`link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`link` (
  `id_link` INT NOT NULL,
  `url` VARCHAR(500) NULL,
  `menu` INT NULL,
  PRIMARY KEY (`id_link`),
  INDEX `id_menu_fk_idx` (`menu` ASC),
  CONSTRAINT `id_menu_fk`
    FOREIGN KEY (`menu`)
    REFERENCES `asi2`.`menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asi2`.`log_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`log_usuario` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `usuario` INT NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT NOW(),
  `accion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_log`),
  INDEX `id_usuario_fk_idx` (`usuario` ASC),
  CONSTRAINT `id_usuario_fk`
    FOREIGN KEY (`usuario`)
    REFERENCES `asi2`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asi2`.`usuario_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asi2`.`usuario_rol` (
  `id_rol` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `id_usuario`),
  INDEX `id_usuario_rol_usuario_fk_idx` (`id_usuario` ASC),
  CONSTRAINT `id_usuario_rol_rol_fk`
    FOREIGN KEY (`id_rol`)
    REFERENCES `asi2`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario_rol_usuario_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `asi2`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



